[env]
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; esptool 5.x required in PATH — platform's bundled 4.x doesn't support ESP32-S3 USB JTAG reliably
upload_protocol = custom
upload_command = esptool --chip esp32s3 write_flash 0x0 $BUILD_DIR/bootloader.bin 0x8000 $BUILD_DIR/partitions.bin 0x10000 $SOURCE
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps = https://github.com/moononournation/Arduino_GFX
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:basic]
build_src_filter = +<basic/>

[env:looper]
build_src_filter = +<looper/>
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
